version: '3.9'

services:
  server:
    command: uvicorn --port 8000 --host 0.0.0.0 --reload main:app
    build:
      context: server
    ports:
      - '8000:8000'
    env_file: .env

volumes:
  root-home:
